HospiceNiagara/Models/FileStorage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

//Paul Boyko Feb 2015

namespace HospiceNiagara.Models
{
    public class FileStorage
    {
        public int ID { get; set; }

        [Required]
        [Display(Name="Mime Type")]
        [StringLength(256)]
        public string MimeType { get; set; }

        [Required(ErrorMessage = "Please name the file")]
        [Display(Name="File Name")]
        [StringLength(100, ErrorMessage = "File name can not be longer than 100 characters")]
        public string FileName { get; set; }

        [Required(ErrorMessage = "Please give the file a description")]
        [StringLength(100, ErrorMessage = "The file discription can not exceed 100 characters")]
        [Display(Name="Description")]
        public string FileDescription { get; set; }

        [Required]
        [Display(Name="Upload Date")]
        public DateTime FileUploadDate { get; set; }

        [Display(Name = "Uploaded By")]
        public string UploadedBy { get; set; }

        public bool HomeImage { get; set; }

        [Display(Name = "Upload Date")]
        public string FileUploadDateString
        {
            get
            {
                return this.FileUploadDate.ToLongDateString();
            }
        }
               
        public virtual ICollection<RoleList> FileStoreUserRoles { get; set; }

        public virtual ICollection<Meeting> Meetings { get; set; }

        public virtual ICollection<SchedType> ScheduleTypes { get; set; }

        public virtual ICollection<Announcement> Announcements { get; set; }

        public virtual ICollection<FileSubCat> FileSubCats { get; set; }
    }

}

HospiceNiagara/Controllers/FileStoragesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HospiceNiagara.Models;
using System.IO;
using HospiceNiagara.ViewModels;
using System.Data.Entity.Infrastructure;
using PagedList;

//Paul Boyko March 2015

namespace HospiceNiagara.Controllers
{
    public class FileStoragesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
      
        // GET: FileStorages
        [Authorize]
        public ActionResult Index(string searchString, int? id)
        {
            var uRole = db.RoleLists;
            var fileR = new FileStorage();
            fileR.FileStoreUserRoles = new List<RoleList>();
            fileR.FileSubCats = new List<FileSubCat>();
            PopulateAssignedRoles(fileR);
            PopulateCatAndSubCat(fileR);

            var allFileForList = db.FileStorages.Where(f => f.ID == 0);

            foreach(var u in uRole)
            {
                 if(User.IsInRole(u.RoleName))
                 {
                     var allFiles = db.FileStorages.Include(r => r.FileStoreUserRoles).Include(fsc => fsc.FileSubCats);
                     allFiles = allFiles.Where(f => f.FileStoreUserRoles.Any(fu => fu.ID == u.ID));
                     allFileForList = allFileForList.Concat(allFiles);
                 }
            }

            bool hasBeenFiltered = false;
            if(id != null && id != 0)
            {
                allFileForList =allFileForList.Where(f => f.FileSubCats.Any(sc => sc.ID == id));
                var searchSubCat = db.FileSubCats.Single(a => a.ID == id);
                var searchCat = db.FileCats.Single(b => b.ID == searchSubCat.FileCatFK);
                var viewModel = new SearchDisplayVM();
                viewModel.SearchSubCatName = searchSubCat.FileSubCatName;
                viewModel.SeachCatName = searchCat.FileCatName;
                ViewBag.SearchCat = viewModel;
                hasBeenFiltered = true;
            }
    
            if(!String.IsNullOrEmpty(searchString))
            {
                allFileForList = allFileForList.Where(f => f.FileDescription.ToUpper().Contains(searchString.ToUpper()) || f.FileName.ToUpper().Contains(searchString.ToUpper()));
                var viewModel = new SearchDisplayVM();
                viewModel.SeachCatName = "User Searched";
                viewModel.SearchSubCatName = searchString;
                ViewBag.SearchCat = viewModel;
                hasBeenFiltered = true;
            }
            if(hasBeenFiltered == true)
            {
                ViewData["Files"] = allFileForList.OrderByDescending(f => f.FileUploadDate).ToList().Distinct();
            }
            else
            {
                ViewData["Files"] = allFileForList.OrderByDescending(f => f.FileUploadDate).ToList().Distinct().Take(20);
            }
            
                      
            return View();
        }

        //Admin List
        [Authorize(Roles = "Administrator")]
        public ActionResult AdminList(int page = 1, int pageSize = 50)
        {
            List<FileStorage> Files = db.FileStorages.OrderBy(a => a.FileUploadDate).ToList();
            PagedList<FileStorage> FilesWithPage = new PagedList<FileStorage>(Files, page, pageSize);

            return View(FilesWithPage);
        }

        public ActionResult UploadNewFile()
        {
            var fileR = new FileStorage();
            fileR.FileStoreUserRoles = new List<RoleList>();
            fileR.FileSubCats = new List<FileSubCat>();
            PopulateAssignedRoles(fileR);
            PopulateCatAndSubCat(fileR);

            return View();
        }

        [HttpGet]
        public ActionResult GetList(string s)
        {
            if (Request.IsAjaxRequest())
            {
                // Find files that have the search string in either the FileName or FileDescription fields and return only the 10 first results.
                var results = db.FileStorages.Where(x => x.FileName.Contains(s) || x.FileDescription.Contains(s)).Take(10).OrderBy(x => x.FileName);
                return PartialView("_SearchList", results);
                
                // If you want to handle presentation of the data on the client side:
                // you can, return a Json Object instead
                // return Json(results, JsonRequestBehavior.AllowGet)
                
            }
             //if it's not an ajax call, we'll tell the browser we didn't find anything. (404 error)
            return new HttpNotFoundResult();
        }

        [HttpPost]
        [OnAction(ButtonName = "UploadNewFile")]
        [Authorize(Roles = "Administrator, Upload Resources")]
        [HandleError()]
        public ActionResult UploadNewFile(string fileDescription, bool homeImage, string[] selectedRoles, string[] selectedSubCats)
        {
            DateTime uploadDate = DateTime.Now;
            string uploadedBy = User.Identity.Name;
            string mimeType = Request.Files[0].ContentType;
            string fileName = Path.GetFileName(Request.Files[0].FileName);
            int fileLenght = Request.Files[0].ContentLength;

            var path = Path.Combine(Server.MapPath("~/Uploads"), fileName);
            if (System.IO.File.Exists(path))
            {
                TempData["Duplicate"] = "<script type='text/javascript'>window.alert('The file " + fileName + " already exists. Please ensure that the file you are submitting is not already uploaded.'); window.history.back();</script>";
                return RedirectToAction("Index");
            }
            try
            {
                if (!(fileName == "" || fileLenght == 0))
                {
                    FileStorage newFile = new FileStorage
                    {
                        MimeType = mimeType,
                        FileName = fileName,
                        FileDescription = fileDescription,
                        HomeImage = homeImage,
                        FileUploadDate = uploadDate,
                        UploadedBy = uploadedBy
                    };
                    if (selectedRoles != null)
                    {
                        newFile.FileStoreUserRoles = new List<RoleList>();
                        foreach (var r in selectedRoles)
                        {
                            var roleToAdd = db.RoleLists.Find(int.Parse(r));
                            newFile.FileStoreUserRoles.Add(roleToAdd);
                        }
                    }
                    else
                    {
                        newFile.FileStoreUserRoles = new List<RoleList>();
                        var roleToAdd = db.RoleLists.Single(r => r.RoleName == "Administrator");
                        newFile.FileStoreUserRoles.Add(roleToAdd);
                    }

                    if (selectedSubCats != null)
                    {
                        newFile.FileSubCats = new List<FileSubCat>();
                        foreach (var sc in selectedSubCats)
                        {
                            var subCatToAdd = db.FileSubCats.Find(int.Parse(sc));
                            newFile.FileSubCats.Add(subCatToAdd);
                        }
                    }
                    //Saves File to the Uploads folder
                    HttpPostedFileBase folderfile = Request.Files[0];
                    if (folderfile.ContentLength > 0)
                    {
                        var folderfileName = Path.GetFileName(folderfile.FileName);
                        path = Path.Combine(Server.MapPath("~/Uploads"), fileName);
                        folderfile.SaveAs(path);
                    }

                    //Other File information is stored in the DB
                    db.FileStorages.Add(newFile);
                    db.SaveChanges();
                }
                else
                {
                    TempData["Duplicate"] = "<script type='text/javascript'>window.alert('Please Select A File To Upload'); window.history.back();</script>";
                    return RedirectToAction("Index");
                }

            }
            catch
            {

            }
            return Content("<script type='text/javascript'>window.close();</script>");
        }


        [HttpPost]
        [OnAction(ButtonName = "UploadFile")]
        [Authorize(Roles = "Administrator, Upload Resources")]
        [HandleError()]
        public ActionResult Index(string fileDescription, bool homeImage, string[] selectedRoles, string[] selectedSubCats)
        {
            DateTime uploadDate = DateTime.Now;
            string uploadedBy = User.Identity.Name;
            string mimeType = Request.Files[0].ContentType;
            string fileName = Path.GetFileName(Request.Files[0].FileName);
            int fileLenght = Request.Files[0].ContentLength;

            var path = Path.Combine(Server.MapPath("~/Uploads"), fileName);
            if(System.IO.File.Exists(path))
            {
                TempData["Duplicate"] = "<script type='text/javascript'>window.alert('The file " + fileName + " already exists. Please ensure that the file you are submitting is not already uploaded.');</script>";
                return RedirectToAction("Index");
            }

            try
            {
                if (!(fileName == "" || fileLenght == 0))
                {
                    FileStorage newFile = new FileStorage
                    {
                        MimeType = mimeType,
                        FileName = fileName,
                        FileDescription = fileDescription,
                        HomeImage = homeImage,
                        FileUploadDate = uploadDate,
                        UploadedBy = uploadedBy
                    };
                    if (selectedRoles != null)
                    {

HospiceNiagara/Views/FileStorages/AdminList.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<HospiceNiagara.Models.FileStorage>

@{
    ViewBag.Title = "AdminList";
}

<h2>AdminList</h2>

@{ Html.BeginForm("BatchDelete", "FileStorages", FormMethod.Post, new { name = "tableForm" }); }
<div>
    <a class="btn btn-default" href="javascript:(function(){document.tableForm.submit();return void(0);})()">
        Delete selected Files
    </a>
</div>
<table class="table">
    <tr>
        <th>
            Select
        </th>
        <th>
            File Name
        </th>
        <th>
            Desc
        </th>
        <th>
            Uploade Date
        </th>
        <th>
            Uploaded By
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            <input type="checkbox" name="deleteInputs" value="@item.ID" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileDescription)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileUploadDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UploadedBy)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) 
            @Html.ActionLink("Details", "Details", new { id=item.ID }) 
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>


<div class="text-center">
    <div class="center-block">
        @Html.PagedListPager(Model, page => Url.Action("AdminList", new { page, pageSize = Model.PageSize }))
        Showing @Model.FirstItemOnPage to @Model.LastItemOnPage of @Model.TotalItemCount Files
    </div>
</div>

@{ Html.EndForm(); }

HospiceNiagara/Views/FileStorages/CloseNewFileWindow.cshtml
<script type="text/javascript">
    window.close();
</script>

HospiceNiagara/Views/FileStorages/Delete.cshtml
@model HospiceNiagara.Models.FileStorage

@{
    ViewBag.Title = "Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <div>
        <div id="storageimage">

            @{
                if (Model.MimeType.Contains("image"))
                {
                    <img src="~/Uploads/@Model.FileName"/>
                }
            }
        </div>

    </div>
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.FileDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileDescription)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>
        
        <dt>
            @Html.DisplayNameFor(model => model.MimeType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MimeType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileUploadDateString)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileUploadDateString)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

HospiceNiagara/Views/FileStorages/Details.cshtml
@model HospiceNiagara.Models.FileStorage

@{
    ViewBag.Title = "Details";
}

<div class="col-md-12">
    <div class="panel panel-success ">
        <div class="panel-heading">
            File Details
        </div>
        <div id="fileDetailsBody" class="panel-body">
                @{
                    if (Model.MimeType.Contains("image"))
                    {
                        <img style="width:100%" src="~/Uploads/@Model.FileName"/>
                    }
                    else if (Model.MimeType.Contains("pdf"))
                    {
                        <object data="~/Uploads/@Model.FileName" type="application/pdf" class="col-md-12" height="700">
                            alt : <a href="~/Uploads/@Model.FileName">@Model.FileName</a>
                        </object>
                    }
                }
            <div id="fileinformation">
                <dl class="dl-horizontal">

                    <dt>
                        @Html.DisplayNameFor(model => model.FileDescription)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.FileDescription)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.FileName)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.FileName)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.MimeType)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.MimeType)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.FileUploadDateString)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.FileUploadDateString)
                    </dd>

                    @if (User.IsInRole("Administrator"))
                    {
                        <dt>
                            @Html.DisplayNameFor(model => model.UploadedBy)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.UploadedBy)
                        </dd>
                    }
                </dl>
            </div>
        </div>
        <p class="text-center">
            @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
            @Html.ActionLink("Back to List", "Index")
        </p>
    </div>
</div>
        

HospiceNiagara/Views/FileStorages/Edit.cshtml
@model HospiceNiagara.Models.FileStorage

@{
    ViewBag.Title = "Edit";
}
@*Initialize filters and gets current url*@
@{
    List<HospiceNiagara.ViewModels.FileCatVM> cat = ViewBag.Cat;
    List<HospiceNiagara.ViewModels.FileSubCatVM> subCat = ViewBag.FileSubCat;
}
<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

 
        <div class="form-group">
            @Html.LabelFor(model => model.FileDescription , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MimeType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.MimeType)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.FileName)
            </div>
        </div>

        @if (User.IsInRole("Administrator"))
        {
            <div class="form-group">
                <label class="control-label col-md-2" for="HomeImage">Use as a Homescreen Image</label>
                <div class="col-md-10" style="padding-top:15px">
                    @Html.EditorFor(model => model.HomeImage, "", new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
        }

        <div class="form-group">
            <label class="control-label col-md-2">Select Roles</label>
            <div class="col-md-offset-2 col-md-10">
                <table class="table">
                    <tr>
                    @{
                    int cnt = 0;
                    List<HospiceNiagara.ViewModels.RoleVM> roles = ViewBag.RolesLists;
                    foreach(var r in roles)
                            {
                                if (cnt++ % 2 == 0)
                                {
                                    @:</tr><tr>
                                }
                                @:<td>
                                    <input type="checkbox"
                                    class="chkRoles"
                                    name="selectedRoles"
                                    value="@r.RoleID"
                                    @(Html.Raw(r.RoleAssigned ? "checked=\"checked\"" : "")) />
                                        @Html.DisplayFor(modelItem => r.RoleName)
                                @:</td>                  
                            }
                    @:</tr>
                    }
                    </table>
            </div>
        </div>

        @foreach (var cats in cat)
        {
            @:<div class="form-group">
                <label class="control-label col-md-2">@Html.DisplayFor(modelItem => cats.FileCatName)</label>
                <div class="col-md-10">
                    <table class="table">
                        @foreach (var sc in subCat)
                        {
                            if (cats.ID == sc.FileCatFK)
                            {
                                <tr>
                                    <td style="padding-left:15px; width:50%;">
                                        @sc.FileSubCatName
                                    </td>
                                    <td>
                                        <input type="checkbox"
                                               name="selectedSubCats"
                                               value="@sc.ID"
                                               @(Html.Raw(sc.FileSubCatAssigned ? "checked=\"checked\"" : "")) />
                                    </td>
                                </tr>

                            }
                        }
                    </table>
                </div>
            @:</div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>

        </div>
    </div>

}  

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        $(document).ready(function () {
            $("[type='checkbox']").bootstrapSwitch();
        });
</script>
}

HospiceNiagara/Views/FileStorages/FileError.cshtml
@{
    ViewBag.Title = "FileError";
}

<h1 class="text-danger">Error Creating Resource.</h1>
<h4 class="text-danger">Please Select A File To Upload</h4>

HospiceNiagara/Views/FileStorages/UploadNewFile.cshtml
@model HospiceNiagara.Models.FileStorage

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Upload File</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link href="~/Content/bootstrap-switch.css" rel="stylesheet">
    <script type="text/javascript" src="~/Scripts/bootstrap-switch.js"></script>
    <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
    @Scripts.Render("~/bundles/jqueryval")
    @{
        List<HospiceNiagara.ViewModels.FileCatVM> cat = ViewBag.Cat;
        List<HospiceNiagara.ViewModels.FileSubCatVM> subCat = ViewBag.FileSubCat;
    }
</head>
<body>
    <div class="container">
        @using (Html.BeginForm("UploadNewFile", "FileStorages", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    <label class="control-label" style="padding-left:15px" for="fileDescription">Description</label>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.FileDescription, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FileDescription, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-12">
                        <input type="file" name="FileUpload" class="" />
                        @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label" style="padding-left:15px" for="HomeImage">Use as a Homescreen Image</label>
                    <div class="col-md-12">
                        @Html.EditorFor(model => model.HomeImage, "", new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                        
                <div class="form-group">
                    <label class="control-label" style="padding-left:15px">Visible to</label>
                    <div class="col-md-12">
                        <table class="table">
                            <tr>
                            @{
                                int cnt = 0;
                                List<HospiceNiagara.ViewModels.RoleVM> roles = ViewBag.RolesLists;
                                foreach(var r in roles)
                                {
                                    if (cnt++ % 2 == 0)
                                    {
                                        @:</tr><tr>
                                    }
                                    @:<td>
                                        <input type="checkbox"
                                        class="chkRoles"
                                        name="selectedRoles"
                                        value="@r.RoleID"
                                        @(Html.Raw(r.RoleAssigned ? "checked=\"checked\"" : "")) />
                                        <br />
                                        <div class="text-left">
                                            @Html.DisplayFor(modelItem => r.RoleName)
                                        </div>
                                    @:</td>         
                                }
                                @:</tr>
                            }
                    </table>
                    </div>
                </div>
                @*<h4>Categories</h4>*@
                @foreach (var cats in cat)
                {
                    @:<div class="form-group">
                        <label class="control-label" style="padding-left:15px">@Html.DisplayFor(modelItem => cats.FileCatName)</label>
                        <table class="table">
                            @foreach (var sc in subCat)
                            {
                                if (cats.ID == sc.FileCatFK)
                                {
                                    <tr>
                                        <td style="padding-left:15px; width:50%;">
                                            @sc.FileSubCatName
                                        </td>
                                        <td>
                                            <input type="checkbox"
                                                    name="selectedSubCats"
                                                    value="@sc.ID"
                                                    @(Html.Raw(sc.FileSubCatAssigned ? "checked=\"checked\"" : "")) />
                                        </td>
                                    </tr>
                                            
                                }
                            }
                        </table>
                    @:</div>
                }
                        
                <div class="form-group">
                    <div class="col-md-10">
                        <input type="submit" value="Create" name="UploadNewFile" class="btn btn-primary"/>
                        @Html.ActionLink("Cancel", null, null, new { @id="linkCancel" })
                    </div>
                </div>
            </div>
                    
        }
    </div>

        <script>
        $(document).ready(function () {
            $("[type='checkbox']").bootstrapSwitch();

            $("#linkCancel").click(function () {
                window.close();
            });
        });
        </script>
    
</body>
</html>

HospiceNiagara/Views/FileStorages/_SearchList.cshtml
@model IEnumerable<HospiceNiagara.Models.FileStorage>

<ul class="search-result-list list-group">
    @foreach (var item in Model)
    {
        <li class="search-result-item list-group-item" data-file-id="@item.ID">@Html.DisplayFor(modelItem => item.FileDescription) - @item.FileUploadDateString</li>
    }
</ul>

@*
    The below is another possible (more detailed) way to show your results.

    Its up to you whether you want to use it, it just depends on your preference, your available space and whether you want to
    go to the trouble of using CSS to properly format it. Personally, I would at least show the file name and date.

    <ul class="search-result-item" data-file-id="@item.ID">
        <div class="row">
            <div class="col-md-6"><strong>@Html.DisplayFor(modelItem => item.FileName)</strong></div>
            <div class="col-md-6"><small><em>@Html.DisplayFor(modelItem => item.FileUploadDate)</em></small></div>
        </div>
        <div class="row">
            <div class="col-md-12">
                @Html.DisplayFor(modelItem => item.FileDescription)
            </div>
        </div>
    </ul>
*@
    
@* 
    #Commenting the below out in case they become useful in the future

    @Html.DisplayFor(modelItem => item.FileContent)
    @Html.DisplayFor(modelItem => item.MimeType)
*@